version: '3'

networks:
  default:
    external:
      name: root_default

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=lucas-sandery
    #links:
    #  - postgis_1
    ports:
      - 8080:8080