version: '3'

networks:
  default:
    external:
      name: root_default

volumes:
  postgis_1_data:

services:
  postgis_1:
    image: kartoza/postgis:latest
    #image: postgres
    container_name: postgis_1
    restart: always
    volumes:
      - postgis_1_data:/var/lib/postgresql/data
      #- /var/lib/docker/volumes/root_pgdata/_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_DBNAME: gis
      POSTGRES_PASSWORD: example
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5434:5432
  
  postgis_2:
    image: kartoza/postgis:latest
    #image: postgres
    container_name: postgis_2
    restart: always
    volumes:
      - /mnt/volume_nyc1_02:/mnt/volume_nyc1_02
      - /mnt/volume_nyc1_02/pg_massive:/var/lib/postgresql/11/main
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_DBNAME: gis
      POSTGRES_PASSWORD: example
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5436:5432
    shm_size: 1g
