version: '3.7'

networks:
  default:
    external:
      name: root_default

services:
  julia_jbs3hp:
    image: julia/latest
    container_name: julia_jbs3hp
    volumes:
        - /home/jbs3hp:/home/jbs3hp
        - /home/sdad:/home/sdad
        - /mnt/volume_nyc1_01:/mnt/volume_nyc1_01         
        - /mnt/volume_nyc1_02:/mnt/volume_nyc1_02
        - /mnt/volume_nyc1_03:/mnt/volume_nyc1_03
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    ports:
        - "10000:8888"
    environment:
      - PASSWORD=password
      - USER=jbs3hp
      - USERID=1027
