---
title: "R Notebook"
output: html_notebook
---

```{r}

col_delim <- "|"
col_num <- 145
col_delim_num <- col_num - 1
file_path <- "/project/biocomplexity/sdad/projects_data/usda/bb/original/corelogic/8state/TaxHistory.Tax_History_05.csv"
file_ext <- tools::file_ext(file_path)
file_path_no_ext <- tools::file_path_sans_ext(file_path)
cut_col_path <- paste0(file_path_no_ext, "_", col_num,"cols.", file_ext)
ascii_path <- paste0(tools::file_path_sans_ext(cut_col_path), "_ascii.", file_ext)
no_quote_path <- paste0(tools::file_path_sans_ext(ascii_path), "_noqt.", file_ext)

Sys.setenv(col_delim=col_delim)  
Sys.setenv(col_num=col_num)
Sys.setenv(col_delim_num=col_delim_num)
Sys.setenv(file_path=file_path)
Sys.setenv(cut_col_path=cut_col_path)
Sys.setenv(ascii_path=ascii_path)
Sys.setenv(no_quote_path=no_quote_path)
Sys.setenv(PGUSER=Sys.getenv("db_usr"))
Sys.setenv(PGPASSWORD=Sys.getenv("db_pwd"))

```


```{bash}
# select columns
cut -d "$col_delim" -f 1-$col_num $file_path > $cut_col_path
```

```{bash}
# remove non-ascii
tr -cd '\11\12\15\40-\176' < $cut_col_path > $ascii_path
```

```{bash}
sed 's/\"//g' < $ascii_path > $no_quote_path
```

```{bash}
# validate number of delimiters
#echo $col_delim'\n'
tr -cd $col_delim'\n' < $no_quote_path | awk 'length!='$col_delim_num' {print NR}'
```

```{bash}
# create copy command for upload
# upload NO QUOTE
echo "psql -U $PGUSER -h postgis1 -d sdad -c \"\copy corelogic_usda.tax_hist_05 from $no_quote_path WITH (FORMAT 'csv', DELIMITER E'\|', QUOTE E'\b', HEADER);\""
```


```{bash}
# create trigram indexes
#for (i in c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10")) {
#  sql <- paste0("CREATE INDEX corelogic_sdad_tax_hist_", i, "_fips_code_trgm_idx ON corelogic_sdad.tax_hist_", i, " USING GIST (fips_code gist_trgm_ops);")
#}
col="fips_code"
for i in 01 02 03 04 05 06 07 08 09 10
do
	sql="CREATE INDEX corelogic_sdad_tax_hist_"$i"_fips_code_trgm_idx ON corelogic_sdad.tax_hist_"$i" USING GIST ("$col" gist_trgm_ops);"
	echo $sql
done
```



# BUILD STATE TABLES
```{r}
source("db_connection.R")
con <- get_db_conn()
sql <- "select \"STATEFP\" fips_code_st, lower(\"STUSPS\") abbrev, \"NAME\" st_name from gis_census_cb.cb_2018_us_state_500k;"
state_codes <- DBI::dbGetQuery(con, sql)
DBI::dbDisconnect(con)

#for (i in 1:nrow(state_codes)) {
for (i in 46:56) {
  fips_code_st <- state_codes[i,]$fips_code_st
  abbrev <- state_codes[i,]$abbrev
  table_name <- paste0("corelogic_prop_tax_2003_2019.", abbrev, "_pl_prop_tax")
  
  con <- get_db_conn()
  sql <- paste0("select * into ", table_name, " from (
                  select * from corelogic_sdad.tax_hist_01 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_02 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_03 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_04 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_05 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_06 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_07 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_08 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_09 where fips_code like '", fips_code_st,"%'
                  union all
                  select * from corelogic_sdad.tax_hist_10 where fips_code like '", fips_code_st,"%'
                ) t")
  #print(sql)
  DBI::dbGetQuery(con, sql)
  DBI::dbDisconnect(con)
}

```

```{r}
source("db_connection.R")
con <- get_db_conn()
sql <- "SELECT table_name FROM information_schema.tables WHERE table_schema = 'corelogic_prop_tax_2003_2019'"
table_names <- DBI::dbGetQuery(con, sql)
DBI::dbDisconnect(con)

for (i in 1:nrow(table_names)) {
  table_name <- table_names[i,]
  
  con <- get_db_conn()
  sql <- paste0("SELECT                             
                    tablename,
                    indexname,
                    indexdef
                FROM
                    pg_indexes
                WHERE
                    tablename = '", table_name,"' 
                ORDER BY
                    tablename,
                    indexname;")
  idx <- DBI::dbGetQuery(con, sql)
  if (nrow(idx) == 0) {
    sql <- paste0("CREATE INDEX ", table_name,"_tax_year_idx ON corelogic_prop_tax_2003_2019.", table_name," (tax_year);")
    print(paste("creating index on table", table_name))
    DBI::dbGetQuery(con, sql)
  }
  DBI::dbDisconnect(con)
}

```