version: '2'

networks:
  default:
    external:
      name: root_default

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iwnftp
      - MYSQL_PASSWORD=iwnftp
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8082:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always